export default [
  {
    InsId: 1,
    InsName: '-||-',
    InsType: 1,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 1,
        ParamName: '',
        ParamType: 1644077057,
        InsId: 1,
      },
    ],
    IsCanUse: true,
    Comment: '常开触点',
    IsIEC61131: true,
    InsTreeIconIndex: 19,
  },
  {
    InsId: 2,
    InsName: '-|/|-',
    InsType: 1,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 2,
        ParamName: '',
        ParamType: 1644077057,
        InsId: 2,
      },
    ],
    IsCanUse: true,
    Comment: '常闭触点',
    IsIEC61131: true,
    InsTreeIconIndex: 19,
  },
  {
    InsId: 3,
    InsName: '-|I|-',
    InsType: 1,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 3,
        ParamName: '',
        ParamType: 172033,
        InsId: 3,
      },
    ],
    IsCanUse: true,
    Comment: '立即常开触点',
    IsIEC61131: true,
    InsTreeIconIndex: 19,
  },
  {
    InsId: 4,
    InsName: '-|/I|-',
    InsType: 1,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 4,
        ParamName: '',
        ParamType: 172033,
        InsId: 4,
      },
    ],
    IsCanUse: true,
    Comment: '立即常闭触点',
    IsIEC61131: true,
    InsTreeIconIndex: 19,
  },
  {
    InsId: 5,
    InsName: 'NCR',
    InsType: 3,
    InsGroup: 0,
    ParamsNumber: 2,
    Params: [
      {
        InsParamId: 5,
        ParamName: 'IN',
        ParamType: 1644081153,
        InsId: 5,
      },
      {
        InsParamId: 6,
        ParamName: 'Q',
        ParamType: 1644081153,
        InsId: 5,
      },
    ],
    IsCanUse: true,
    Comment: '逻辑结果取反',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 6,
    InsName: '-(NUL)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 0,
    Params: [
      {
        InsParamId: 7,
        ParamName: '',
        ParamType: 27082753,
        InsId: 6,
      },
    ],
    IsCanUse: true,
    Comment: '网络结束',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 7,
    InsName: '-( )',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 8,
        ParamName: '',
        ParamType: 27082753,
        InsId: 7,
      },
    ],
    IsCanUse: true,
    Comment: '线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 8,
    InsName: '-(/)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 9,
        ParamName: '',
        ParamType: 27082753,
        InsId: 8,
      },
    ],
    IsCanUse: true,
    Comment: '取反线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 9,
    InsName: '-(I)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 10,
        ParamName: '',
        ParamType: 344065,
        InsId: 9,
      },
    ],
    IsCanUse: true,
    Comment: '立即线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 10,
    InsName: '-(S)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 11,
        ParamName: '',
        ParamType: 27082753,
        InsId: 10,
      },
    ],
    IsCanUse: true,
    Comment: '置位线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 11,
    InsName: '-(SI)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 12,
        ParamName: '',
        ParamType: 344065,
        InsId: 11,
      },
    ],
    IsCanUse: true,
    Comment: '立即置位线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 12,
    InsName: '-(R)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 13,
        ParamName: '',
        ParamType: 27082753,
        InsId: 12,
      },
    ],
    IsCanUse: true,
    Comment: '复位线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 13,
    InsName: '-(RI)',
    InsType: 2,
    InsGroup: 0,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 14,
        ParamName: '',
        ParamType: 344065,
        InsId: 13,
      },
    ],
    IsCanUse: true,
    Comment: '立即复位线圈',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 14,
    InsName: 'R_TRIG',
    InsType: 3,
    InsGroup: 0,
    ParamsNumber: 2,
    Params: [
      {
        InsParamId: 15,
        ParamName: 'CLK',
        ParamType: 1644081153,
        InsId: 14,
      },
      {
        InsParamId: 16,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 14,
      },
    ],
    IsCanUse: true,
    Comment: '取上升沿',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 15,
    InsName: 'F_TRIG',
    InsType: 3,
    InsGroup: 0,
    ParamsNumber: 2,
    Params: [
      {
        InsParamId: 17,
        ParamName: 'CLK',
        ParamType: 1644081153,
        InsId: 15,
      },
      {
        InsParamId: 18,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 15,
      },
    ],
    IsCanUse: true,
    Comment: '取下降沿',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 16,
    InsName: 'RS',
    InsType: 4,
    InsGroup: 0,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 19,
        ParamName: 'S',
        ParamType: 1644077057,
        InsId: 16,
      },
      {
        InsParamId: 20,
        ParamName: 'R1',
        ParamType: 1644077057,
        InsId: 16,
      },
      {
        InsParamId: 21,
        ParamName: 'Q1',
        ParamType: 27082753,
        InsId: 16,
      },
    ],
    IsCanUse: true,
    Comment: 'RS触发器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 17,
    InsName: 'SR',
    InsType: 4,
    InsGroup: 0,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 22,
        ParamName: 'S1',
        ParamType: 1644077057,
        InsId: 17,
      },
      {
        InsParamId: 23,
        ParamName: 'R',
        ParamType: 1644077057,
        InsId: 17,
      },
      {
        InsParamId: 24,
        ParamName: 'Q1',
        ParamType: 27082753,
        InsId: 17,
      },
    ],
    IsCanUse: true,
    Comment: 'SR触发器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 18,
    InsName: 'NOP',
    InsType: 3,
    InsGroup: 0,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 25,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 18,
      },
      {
        InsParamId: 26,
        ParamName: 'N',
        ParamType: 45072,
        InsId: 18,
      },
      {
        InsParamId: 27,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 18,
      },
    ],
    IsCanUse: true,
    Comment: '空指令',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 19,
    InsName: 'ALT',
    InsType: 3,
    InsGroup: 0,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 28,
        ParamName: 'IN',
        ParamType: 1644081153,
        InsId: 19,
      },
      {
        InsParamId: 29,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 19,
      },
      {
        InsParamId: 30,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 19,
      },
    ],
    IsCanUse: true,
    Comment: '反转',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 20,
    InsName: 'MOVE',
    InsType: 3,
    InsGroup: 14,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 31,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 20,
      },
      {
        InsParamId: 32,
        ParamName: 'IN',
        ParamType: 503230718,
        InsId: 20,
      },
      {
        InsParamId: 33,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 20,
      },
      {
        InsParamId: 34,
        ParamName: 'OUT',
        ParamType: 503230718,
        InsId: 20,
      },
    ],
    IsCanUse: true,
    Comment: '赋值',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 21,
    InsName: 'BLKMOVE',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 35,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 21,
      },
      {
        InsParamId: 36,
        ParamName: 'IN',
        ParamType: 503226622,
        InsId: 21,
      },
      {
        InsParamId: 37,
        ParamName: 'N',
        ParamType: 27177090,
        InsId: 21,
      },
      {
        InsParamId: 38,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 21,
      },
      {
        InsParamId: 39,
        ParamName: 'OUT',
        ParamType: 295518462,
        InsId: 21,
      },
    ],
    IsCanUse: true,
    Comment: '块转移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 22,
    InsName: 'FILL',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 40,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 22,
      },
      {
        InsParamId: 41,
        ParamName: 'IN',
        ParamType: 45058,
        InsId: 22,
      },
      {
        InsParamId: 42,
        ParamName: 'N',
        ParamType: 45058,
        InsId: 22,
      },
      {
        InsParamId: 43,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 22,
      },
      {
        InsParamId: 44,
        ParamName: 'OUT',
        ParamType: 25772162,
        InsId: 22,
      },
    ],
    IsCanUse: true,
    Comment: '块赋值',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 23,
    InsName: 'SWAP',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 45,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 23,
      },
      {
        InsParamId: 46,
        ParamName: 'IN',
        ParamType: 27041932,
        InsId: 23,
      },
      {
        InsParamId: 47,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 23,
      },
    ],
    IsCanUse: true,
    Comment: 'WORD高低字节或DWORD高低字互换',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 24,
    InsName: 'GT',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 48,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 24,
      },
      {
        InsParamId: 49,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 24,
      },
      {
        InsParamId: 50,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 24,
      },
      {
        InsParamId: 51,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 24,
      },
    ],
    IsCanUse: true,
    Comment: '大于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 25,
    InsName: 'GE',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 52,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 25,
      },
      {
        InsParamId: 53,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 25,
      },
      {
        InsParamId: 54,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 25,
      },
      {
        InsParamId: 55,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 25,
      },
    ],
    IsCanUse: true,
    Comment: '大于等于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 26,
    InsName: 'EQ',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 56,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 26,
      },
      {
        InsParamId: 57,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 26,
      },
      {
        InsParamId: 58,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 26,
      },
      {
        InsParamId: 59,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 26,
      },
    ],
    IsCanUse: true,
    Comment: '等于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 27,
    InsName: 'NE',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 60,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 27,
      },
      {
        InsParamId: 61,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 27,
      },
      {
        InsParamId: 62,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 27,
      },
      {
        InsParamId: 63,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 27,
      },
    ],
    IsCanUse: true,
    Comment: '不等于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 28,
    InsName: 'LT',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 64,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 28,
      },
      {
        InsParamId: 65,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 28,
      },
      {
        InsParamId: 66,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 28,
      },
      {
        InsParamId: 67,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 28,
      },
    ],
    IsCanUse: true,
    Comment: '小于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 29,
    InsName: 'LE',
    InsType: 3,
    InsGroup: 2,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 68,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 29,
      },
      {
        InsParamId: 69,
        ParamName: 'IN1',
        ParamType: 503230706,
        InsId: 29,
      },
      {
        InsParamId: 70,
        ParamName: 'IN2',
        ParamType: 503230706,
        InsId: 29,
      },
      {
        InsParamId: 71,
        ParamName: 'OUT',
        ParamType: 27082753,
        InsId: 29,
      },
    ],
    IsCanUse: true,
    Comment: '小于等于',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 30,
    InsName: 'NOT',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 72,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 30,
      },
      {
        InsParamId: 73,
        ParamName: 'IN',
        ParamType: 27177102,
        InsId: 30,
      },
      {
        InsParamId: 74,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 30,
      },
      {
        InsParamId: 75,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 30,
      },
    ],
    IsCanUse: true,
    Comment: '按位取反',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 31,
    InsName: 'AND',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 76,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 31,
      },
      {
        InsParamId: 77,
        ParamName: 'IN1',
        ParamType: 27177102,
        InsId: 31,
      },
      {
        InsParamId: 78,
        ParamName: 'IN2',
        ParamType: 27177102,
        InsId: 31,
      },
      {
        InsParamId: 79,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 31,
      },
      {
        InsParamId: 80,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 31,
      },
    ],
    IsCanUse: true,
    Comment: '按位与',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 32,
    InsName: 'ANDN',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 81,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 32,
      },
      {
        InsParamId: 82,
        ParamName: 'IN1',
        ParamType: 27177102,
        InsId: 32,
      },
      {
        InsParamId: 83,
        ParamName: 'IN2',
        ParamType: 27177102,
        InsId: 32,
      },
      {
        InsParamId: 84,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 32,
      },
      {
        InsParamId: 85,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 32,
      },
    ],
    IsCanUse: true,
    Comment: '按位与非',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 33,
    InsName: 'OR',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 86,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 33,
      },
      {
        InsParamId: 87,
        ParamName: 'IN1',
        ParamType: 27177102,
        InsId: 33,
      },
      {
        InsParamId: 88,
        ParamName: 'IN2',
        ParamType: 27177102,
        InsId: 33,
      },
      {
        InsParamId: 89,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 33,
      },
      {
        InsParamId: 90,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 33,
      },
    ],
    IsCanUse: true,
    Comment: '按位或',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 34,
    InsName: 'ORN',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 91,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 34,
      },
      {
        InsParamId: 92,
        ParamName: 'IN1',
        ParamType: 27177102,
        InsId: 34,
      },
      {
        InsParamId: 93,
        ParamName: 'IN2',
        ParamType: 27177102,
        InsId: 34,
      },
      {
        InsParamId: 94,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 34,
      },
      {
        InsParamId: 95,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 34,
      },
    ],
    IsCanUse: true,
    Comment: '按位或非',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 35,
    InsName: 'XOR',
    InsType: 3,
    InsGroup: 3,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 96,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 35,
      },
      {
        InsParamId: 97,
        ParamName: 'IN1',
        ParamType: 27177102,
        InsId: 35,
      },
      {
        InsParamId: 98,
        ParamName: 'IN2',
        ParamType: 27177102,
        InsId: 35,
      },
      {
        InsParamId: 99,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 35,
      },
      {
        InsParamId: 100,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 35,
      },
    ],
    IsCanUse: true,
    Comment: '按位异或',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 36,
    InsName: 'SHL',
    InsType: 3,
    InsGroup: 4,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 101,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 36,
      },
      {
        InsParamId: 102,
        ParamName: 'IN',
        ParamType: 27177102,
        InsId: 36,
      },
      {
        InsParamId: 103,
        ParamName: 'N',
        ParamType: 27177102,
        InsId: 36,
      },
      {
        InsParamId: 104,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 36,
      },
      {
        InsParamId: 105,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 36,
      },
    ],
    IsCanUse: true,
    Comment: '左移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 37,
    InsName: 'ROL',
    InsType: 3,
    InsGroup: 4,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 106,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 37,
      },
      {
        InsParamId: 107,
        ParamName: 'IN',
        ParamType: 27177102,
        InsId: 37,
      },
      {
        InsParamId: 108,
        ParamName: 'N',
        ParamType: 27177102,
        InsId: 37,
      },
      {
        InsParamId: 109,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 37,
      },
      {
        InsParamId: 110,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 37,
      },
    ],
    IsCanUse: true,
    Comment: '循环左移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 38,
    InsName: 'SHL_BLK',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 6,
    Params: [
      {
        InsParamId: 111,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 38,
      },
      {
        InsParamId: 112,
        ParamName: 'S_DATA',
        ParamType: 26124289,
        InsId: 38,
      },
      {
        InsParamId: 113,
        ParamName: 'S_N',
        ParamType: 436121744,
        InsId: 38,
      },
      {
        InsParamId: 114,
        ParamName: 'D_DATA',
        ParamType: 26075137,
        InsId: 38,
      },
      {
        InsParamId: 115,
        ParamName: 'D_N',
        ParamType: 436121744,
        InsId: 38,
      },
      {
        InsParamId: 116,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 38,
      },
    ],
    IsCanUse: true,
    Comment: '块左移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 39,
    InsName: 'SHR',
    InsType: 3,
    InsGroup: 4,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 117,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 39,
      },
      {
        InsParamId: 118,
        ParamName: 'IN',
        ParamType: 27177102,
        InsId: 39,
      },
      {
        InsParamId: 119,
        ParamName: 'N',
        ParamType: 27177102,
        InsId: 39,
      },
      {
        InsParamId: 120,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 39,
      },
      {
        InsParamId: 121,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 39,
      },
    ],
    IsCanUse: true,
    Comment: '右移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 40,
    InsName: 'ROR',
    InsType: 3,
    InsGroup: 4,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 122,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 40,
      },
      {
        InsParamId: 123,
        ParamName: 'IN',
        ParamType: 27177102,
        InsId: 40,
      },
      {
        InsParamId: 124,
        ParamName: 'N',
        ParamType: 27177102,
        InsId: 40,
      },
      {
        InsParamId: 125,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 40,
      },
      {
        InsParamId: 126,
        ParamName: 'OUT',
        ParamType: 27082894,
        InsId: 40,
      },
    ],
    IsCanUse: true,
    Comment: '循环右移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 41,
    InsName: 'SHR_BLK',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 6,
    Params: [
      {
        InsParamId: 127,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 41,
      },
      {
        InsParamId: 128,
        ParamName: 'S_DATA',
        ParamType: 26124289,
        InsId: 41,
      },
      {
        InsParamId: 129,
        ParamName: 'S_N',
        ParamType: 436121744,
        InsId: 41,
      },
      {
        InsParamId: 130,
        ParamName: 'D_DATA',
        ParamType: 26075137,
        InsId: 41,
      },
      {
        InsParamId: 131,
        ParamName: 'D_N',
        ParamType: 436121744,
        InsId: 41,
      },
      {
        InsParamId: 132,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 41,
      },
    ],
    IsCanUse: true,
    Comment: '块右移',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 42,
    InsName: 'BTI',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 133,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 42,
      },
      {
        InsParamId: 134,
        ParamName: 'IN',
        ParamType: 27176962,
        InsId: 42,
      },
      {
        InsParamId: 135,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 42,
      },
      {
        InsParamId: 136,
        ParamName: 'OUT',
        ParamType: 295518224,
        InsId: 42,
      },
    ],
    IsCanUse: true,
    Comment: 'BYTE型转INT型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 43,
    InsName: 'ITB',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 137,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 43,
      },
      {
        InsParamId: 138,
        ParamName: 'IN',
        ParamType: 436121616,
        InsId: 43,
      },
      {
        InsParamId: 139,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 43,
      },
      {
        InsParamId: 140,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 43,
      },
    ],
    IsCanUse: true,
    Comment: 'INT型转BYTE型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 44,
    InsName: 'DITI',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 141,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 44,
      },
      {
        InsParamId: 142,
        ParamName: 'IN',
        ParamType: 94285856,
        InsId: 44,
      },
      {
        InsParamId: 143,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 44,
      },
      {
        InsParamId: 144,
        ParamName: 'OUT',
        ParamType: 295518224,
        InsId: 44,
      },
    ],
    IsCanUse: true,
    Comment: 'DINT型转INT型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 45,
    InsName: 'ITDI',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 145,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 45,
      },
      {
        InsParamId: 146,
        ParamName: 'IN',
        ParamType: 436121616,
        InsId: 45,
      },
      {
        InsParamId: 147,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 45,
      },
      {
        InsParamId: 148,
        ParamName: 'OUT',
        ParamType: 27082784,
        InsId: 45,
      },
    ],
    IsCanUse: true,
    Comment: 'INT型转DINT型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 46,
    InsName: 'DITR',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 149,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 46,
      },
      {
        InsParamId: 150,
        ParamName: 'IN',
        ParamType: 94285856,
        InsId: 46,
      },
      {
        InsParamId: 151,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 46,
      },
      {
        InsParamId: 152,
        ParamName: 'OUT',
        ParamType: 25247808,
        InsId: 46,
      },
    ],
    IsCanUse: true,
    Comment: 'DINT型转REAL型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 47,
    InsName: 'RTDI',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 153,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 47,
      },
      {
        InsParamId: 154,
        ParamName: 'IN',
        ParamType: 25210944,
        InsId: 47,
      },
      {
        InsParamId: 155,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 47,
      },
      {
        InsParamId: 156,
        ParamName: 'OUT',
        ParamType: 27082784,
        InsId: 47,
      },
    ],
    IsCanUse: true,
    Comment: 'REAL型转DINT型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 48,
    InsName: 'BCDTI',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 157,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 48,
      },
      {
        InsParamId: 158,
        ParamName: 'IN',
        ParamType: 27176964,
        InsId: 48,
      },
      {
        InsParamId: 159,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 48,
      },
      {
        InsParamId: 160,
        ParamName: 'OUT',
        ParamType: 295518224,
        InsId: 48,
      },
    ],
    IsCanUse: true,
    Comment: 'BCD转INT型',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 49,
    InsName: 'ITBCD',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 161,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 49,
      },
      {
        InsParamId: 162,
        ParamName: 'IN',
        ParamType: 436121616,
        InsId: 49,
      },
      {
        InsParamId: 163,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 49,
      },
      {
        InsParamId: 164,
        ParamName: 'OUT',
        ParamType: 27082756,
        InsId: 49,
      },
    ],
    IsCanUse: true,
    Comment: 'INT型转BCD',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 50,
    InsName: 'ITA',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 165,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 50,
      },
      {
        InsParamId: 166,
        ParamName: 'IN',
        ParamType: 436121616,
        InsId: 50,
      },
      {
        InsParamId: 167,
        ParamName: 'FMT',
        ParamType: 26779650,
        InsId: 50,
      },
      {
        InsParamId: 168,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 50,
      },
      {
        InsParamId: 169,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 50,
      },
    ],
    IsCanUse: true,
    Comment: 'INT型转ASCII',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 51,
    InsName: 'DITA',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 170,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 51,
      },
      {
        InsParamId: 171,
        ParamName: 'IN',
        ParamType: 94285856,
        InsId: 51,
      },
      {
        InsParamId: 172,
        ParamName: 'FMT',
        ParamType: 26779650,
        InsId: 51,
      },
      {
        InsParamId: 173,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 51,
      },
      {
        InsParamId: 174,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 51,
      },
    ],
    IsCanUse: true,
    Comment: 'DINT型转ASCII',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 52,
    InsName: 'RTA',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 175,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 52,
      },
      {
        InsParamId: 176,
        ParamName: 'IN',
        ParamType: 25210944,
        InsId: 52,
      },
      {
        InsParamId: 177,
        ParamName: 'FMT',
        ParamType: 26779650,
        InsId: 52,
      },
      {
        InsParamId: 178,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 52,
      },
      {
        InsParamId: 179,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 52,
      },
    ],
    IsCanUse: true,
    Comment: 'REAL型转ASCII',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 53,
    InsName: 'HTA',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 180,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 53,
      },
      {
        InsParamId: 181,
        ParamName: 'IN',
        ParamType: 27172866,
        InsId: 53,
      },
      {
        InsParamId: 182,
        ParamName: 'LEN',
        ParamType: 27176962,
        InsId: 53,
      },
      {
        InsParamId: 183,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 53,
      },
      {
        InsParamId: 184,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 53,
      },
    ],
    IsCanUse: true,
    Comment: '十六进制转ASCII',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 54,
    InsName: 'ATH',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 185,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 54,
      },
      {
        InsParamId: 186,
        ParamName: 'IN',
        ParamType: 27172866,
        InsId: 54,
      },
      {
        InsParamId: 187,
        ParamName: 'LEN',
        ParamType: 27176962,
        InsId: 54,
      },
      {
        InsParamId: 188,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 54,
      },
      {
        InsParamId: 189,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 54,
      },
    ],
    IsCanUse: true,
    Comment: 'ASCII转十六进制',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 55,
    InsName: 'ENCO',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 190,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 55,
      },
      {
        InsParamId: 191,
        ParamName: 'IN',
        ParamType: 27176964,
        InsId: 55,
      },
      {
        InsParamId: 192,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 55,
      },
      {
        InsParamId: 193,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 55,
      },
    ],
    IsCanUse: true,
    Comment: '编码',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 56,
    InsName: 'DECO',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 194,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 56,
      },
      {
        InsParamId: 195,
        ParamName: 'IN',
        ParamType: 27176962,
        InsId: 56,
      },
      {
        InsParamId: 196,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 56,
      },
      {
        InsParamId: 197,
        ParamName: 'OUT',
        ParamType: 27082756,
        InsId: 56,
      },
    ],
    IsCanUse: true,
    Comment: '解码',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 57,
    InsName: 'SEG',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 198,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 57,
      },
      {
        InsParamId: 199,
        ParamName: 'IN',
        ParamType: 27176962,
        InsId: 57,
      },
      {
        InsParamId: 200,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 57,
      },
      {
        InsParamId: 201,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 57,
      },
    ],
    IsCanUse: true,
    Comment: '生成七段码',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 58,
    InsName: 'TRUNC',
    InsType: 3,
    InsGroup: 5,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 202,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 58,
      },
      {
        InsParamId: 203,
        ParamName: 'IN',
        ParamType: 25210944,
        InsId: 58,
      },
      {
        InsParamId: 204,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 58,
      },
      {
        InsParamId: 205,
        ParamName: 'OUT',
        ParamType: 27082784,
        InsId: 58,
      },
    ],
    IsCanUse: true,
    Comment: '截去实数的小数部分',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 59,
    InsName: 'ADD',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 206,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 59,
      },
      {
        InsParamId: 207,
        ParamName: 'IN1',
        ParamType: 503230704,
        InsId: 59,
      },
      {
        InsParamId: 208,
        ParamName: 'IN2',
        ParamType: 503230704,
        InsId: 59,
      },
      {
        InsParamId: 209,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 59,
      },
      {
        InsParamId: 210,
        ParamName: 'OUT',
        ParamType: 295518448,
        InsId: 59,
      },
    ],
    IsCanUse: true,
    Comment: '加',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 60,
    InsName: 'SUB',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 211,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 60,
      },
      {
        InsParamId: 212,
        ParamName: 'IN1',
        ParamType: 503230704,
        InsId: 60,
      },
      {
        InsParamId: 213,
        ParamName: 'IN2',
        ParamType: 503230704,
        InsId: 60,
      },
      {
        InsParamId: 214,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 60,
      },
      {
        InsParamId: 215,
        ParamName: 'OUT',
        ParamType: 295518448,
        InsId: 60,
      },
    ],
    IsCanUse: true,
    Comment: '减',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 61,
    InsName: 'MUL',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 216,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 61,
      },
      {
        InsParamId: 217,
        ParamName: 'IN1',
        ParamType: 503230704,
        InsId: 61,
      },
      {
        InsParamId: 218,
        ParamName: 'IN2',
        ParamType: 503230704,
        InsId: 61,
      },
      {
        InsParamId: 219,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 61,
      },
      {
        InsParamId: 220,
        ParamName: 'OUT',
        ParamType: 295518448,
        InsId: 61,
      },
    ],
    IsCanUse: true,
    Comment: '乘',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 62,
    InsName: 'DIV',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 221,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 62,
      },
      {
        InsParamId: 222,
        ParamName: 'IN1',
        ParamType: 503230704,
        InsId: 62,
      },
      {
        InsParamId: 223,
        ParamName: 'IN2',
        ParamType: 503230704,
        InsId: 62,
      },
      {
        InsParamId: 224,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 62,
      },
      {
        InsParamId: 225,
        ParamName: 'OUT',
        ParamType: 295518448,
        InsId: 62,
      },
    ],
    IsCanUse: true,
    Comment: '除',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 63,
    InsName: 'MOD',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 226,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 63,
      },
      {
        InsParamId: 227,
        ParamName: 'IN1',
        ParamType: 503230642,
        InsId: 63,
      },
      {
        InsParamId: 228,
        ParamName: 'IN2',
        ParamType: 503230642,
        InsId: 63,
      },
      {
        InsParamId: 229,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 63,
      },
      {
        InsParamId: 230,
        ParamName: 'OUT',
        ParamType: 295518386,
        InsId: 63,
      },
    ],
    IsCanUse: true,
    Comment: '求余',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 64,
    InsName: 'INC',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 231,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 64,
      },
      {
        InsParamId: 232,
        ParamName: 'IN',
        ParamType: 503230642,
        InsId: 64,
      },
      {
        InsParamId: 233,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 64,
      },
      {
        InsParamId: 234,
        ParamName: 'OUT',
        ParamType: 295518386,
        InsId: 64,
      },
    ],
    IsCanUse: true,
    Comment: '加1',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 65,
    InsName: 'DEC',
    InsType: 3,
    InsGroup: 6,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 235,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 65,
      },
      {
        InsParamId: 236,
        ParamName: 'IN',
        ParamType: 503230642,
        InsId: 65,
      },
      {
        InsParamId: 237,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 65,
      },
      {
        InsParamId: 238,
        ParamName: 'OUT',
        ParamType: 295518386,
        InsId: 65,
      },
    ],
    IsCanUse: true,
    Comment: '减1',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 66,
    InsName: 'SQRT',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 239,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 66,
      },
      {
        InsParamId: 240,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 66,
      },
      {
        InsParamId: 241,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 66,
      },
      {
        InsParamId: 242,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 66,
      },
    ],
    IsCanUse: true,
    Comment: '平方根',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 67,
    InsName: 'LN',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 243,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 67,
      },
      {
        InsParamId: 244,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 67,
      },
      {
        InsParamId: 245,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 67,
      },
      {
        InsParamId: 246,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 67,
      },
    ],
    IsCanUse: true,
    Comment: '自然对数',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 68,
    InsName: 'LG',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 247,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 68,
      },
      {
        InsParamId: 248,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 68,
      },
      {
        InsParamId: 249,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 68,
      },
      {
        InsParamId: 250,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 68,
      },
    ],
    IsCanUse: true,
    Comment: '常用对数',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 69,
    InsName: 'EXP',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 251,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 69,
      },
      {
        InsParamId: 252,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 69,
      },
      {
        InsParamId: 253,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 69,
      },
      {
        InsParamId: 254,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 69,
      },
    ],
    IsCanUse: true,
    Comment: '以e为底的指数',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 70,
    InsName: 'SIN',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 255,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 70,
      },
      {
        InsParamId: 256,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 70,
      },
      {
        InsParamId: 257,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 70,
      },
      {
        InsParamId: 258,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 70,
      },
    ],
    IsCanUse: true,
    Comment: '正弦',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 71,
    InsName: 'COS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 259,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 71,
      },
      {
        InsParamId: 260,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 71,
      },
      {
        InsParamId: 261,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 71,
      },
      {
        InsParamId: 262,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 71,
      },
    ],
    IsCanUse: true,
    Comment: '余弦',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 72,
    InsName: 'TAN',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 263,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 72,
      },
      {
        InsParamId: 264,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 72,
      },
      {
        InsParamId: 265,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 72,
      },
      {
        InsParamId: 266,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 72,
      },
    ],
    IsCanUse: true,
    Comment: '正切',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 73,
    InsName: 'ASIN',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 267,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 73,
      },
      {
        InsParamId: 268,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 73,
      },
      {
        InsParamId: 269,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 73,
      },
      {
        InsParamId: 270,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 73,
      },
    ],
    IsCanUse: true,
    Comment: '反正弦',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 74,
    InsName: 'ACOS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 271,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 74,
      },
      {
        InsParamId: 272,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 74,
      },
      {
        InsParamId: 273,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 74,
      },
      {
        InsParamId: 274,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 74,
      },
    ],
    IsCanUse: true,
    Comment: '反余弦',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 75,
    InsName: 'ATAN',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 275,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 75,
      },
      {
        InsParamId: 276,
        ParamName: 'IN',
        ParamType: 25211072,
        InsId: 75,
      },
      {
        InsParamId: 277,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 75,
      },
      {
        InsParamId: 278,
        ParamName: 'OUT',
        ParamType: 25247936,
        InsId: 75,
      },
    ],
    IsCanUse: true,
    Comment: '反正切',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 76,
    InsName: 'ABS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 279,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 76,
      },
      {
        InsParamId: 280,
        ParamName: 'IN',
        ParamType: 436121840,
        InsId: 76,
      },
      {
        InsParamId: 281,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 76,
      },
      {
        InsParamId: 282,
        ParamName: 'OUT',
        ParamType: 295518448,
        InsId: 76,
      },
    ],
    IsCanUse: true,
    Comment: '绝对值',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 77,
    InsName: 'FOR',
    InsType: 3,
    InsGroup: 7,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 283,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 77,
      },
      {
        InsParamId: 284,
        ParamName: 'INDX',
        ParamType: 26779664,
        InsId: 77,
      },
      {
        InsParamId: 285,
        ParamName: 'INIT',
        ParamType: 33075216,
        InsId: 77,
      },
      {
        InsParamId: 286,
        ParamName: 'FINAL',
        ParamType: 33075216,
        InsId: 77,
      },
      {
        InsParamId: 287,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 77,
      },
    ],
    IsCanUse: true,
    Comment: 'FOR循环',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 78,
    InsName: '-(NEXT)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: 'FOR循环的结束语句',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 79,
    InsName: '-(LBL)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 288,
        ParamName: '',
        ParamType: 1024,
        InsId: 79,
      },
    ],
    IsCanUse: true,
    Comment: '设置语句标签',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 80,
    InsName: '-(JMP)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 289,
        ParamName: '',
        ParamType: 1024,
        InsId: 80,
      },
    ],
    IsCanUse: true,
    Comment: '无条件跳转',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 81,
    InsName: '-(JMPC)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 290,
        ParamName: '',
        ParamType: 1024,
        InsId: 81,
      },
    ],
    IsCanUse: true,
    Comment: '条件跳转',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 82,
    InsName: '-(JMPCN)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 1,
    Params: [
      {
        InsParamId: 291,
        ParamName: '',
        ParamType: 1024,
        InsId: 82,
      },
    ],
    IsCanUse: true,
    Comment: '条件(取反)跳转',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 83,
    InsName: '-(RET)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '无条件退出程序',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 84,
    InsName: '-(RETC)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '条件退出程序',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 85,
    InsName: '-(RETCN)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '条件(取反)退出程序',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 86,
    InsName: '-(END)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '终止整个程序的执行',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 87,
    InsName: '-(STOP)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '将CPU处于STOP状态',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 88,
    InsName: '-(WDR)',
    InsType: 2,
    InsGroup: 7,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '复位看门狗时间',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 89,
    InsName: '-(ENI)',
    InsType: 2,
    InsGroup: 11,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '开中断',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 90,
    InsName: '-(DISI)',
    InsType: 2,
    InsGroup: 11,
    ParamsNumber: 0,
    Params: [],
    IsCanUse: true,
    Comment: '关中断',
    IsIEC61131: true,
    InsTreeIconIndex: 23,
  },
  {
    InsId: 91,
    InsName: 'ATCH',
    InsType: 3,
    InsGroup: 11,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 292,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 91,
      },
      {
        InsParamId: 293,
        ParamName: 'INT',
        ParamType: 41984,
        InsId: 91,
      },
      {
        InsParamId: 294,
        ParamName: 'EVENT',
        ParamType: 45072,
        InsId: 91,
      },
      {
        InsParamId: 295,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 91,
      },
    ],
    IsCanUse: true,
    Comment: '分配中断',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 92,
    InsName: 'DTCH',
    InsType: 3,
    InsGroup: 11,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 296,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 92,
      },
      {
        InsParamId: 297,
        ParamName: 'EVENT',
        ParamType: 45072,
        InsId: 92,
      },
      {
        InsParamId: 298,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 92,
      },
    ],
    IsCanUse: true,
    Comment: '释放中断',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 93,
    InsName: 'READ_RTC',
    InsType: 3,
    InsGroup: 8,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 299,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 93,
      },
      {
        InsParamId: 300,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 93,
      },
      {
        InsParamId: 301,
        ParamName: 'T',
        ParamType: 25772034,
        InsId: 93,
      },
    ],
    IsCanUse: true,
    Comment: '读取实时时钟',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 94,
    InsName: 'SET_RTC',
    InsType: 3,
    InsGroup: 8,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 302,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 94,
      },
      {
        InsParamId: 303,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 94,
      },
      {
        InsParamId: 304,
        ParamName: 'T',
        ParamType: 25731074,
        InsId: 94,
      },
    ],
    IsCanUse: true,
    Comment: '设置实时时钟',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 95,
    InsName: 'XMT',
    InsType: 3,
    InsGroup: 9,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 305,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 95,
      },
      {
        InsParamId: 306,
        ParamName: 'TBL',
        ParamType: 8429570,
        InsId: 95,
      },
      {
        InsParamId: 307,
        ParamName: 'PORT',
        ParamType: 45072,
        InsId: 95,
      },
      {
        InsParamId: 308,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 95,
      },
    ],
    IsCanUse: true,
    Comment: '自由通讯：发送数据',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 96,
    InsName: 'RCV',
    InsType: 3,
    InsGroup: 9,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 309,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 96,
      },
      {
        InsParamId: 310,
        ParamName: 'TBL',
        ParamType: 8429570,
        InsId: 96,
      },
      {
        InsParamId: 311,
        ParamName: 'PORT',
        ParamType: 45072,
        InsId: 96,
      },
      {
        InsParamId: 312,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 96,
      },
    ],
    IsCanUse: true,
    Comment: '自由通讯：接收数据',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 97,
    InsName: 'MBUSR',
    InsType: 3,
    InsGroup: 16,
    ParamsNumber: 10,
    Params: [
      {
        InsParamId: 313,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 97,
      },
      {
        InsParamId: 314,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 97,
      },
      {
        InsParamId: 315,
        ParamName: 'PORT',
        ParamType: 45072,
        InsId: 97,
      },
      {
        InsParamId: 316,
        ParamName: 'SLAVE',
        ParamType: 1644081154,
        InsId: 97,
      },
      {
        InsParamId: 317,
        ParamName: 'FUN',
        ParamType: 45072,
        InsId: 97,
      },
      {
        InsParamId: 318,
        ParamName: 'ADDR',
        ParamType: 412004356,
        InsId: 97,
      },
      {
        InsParamId: 319,
        ParamName: 'COUNT',
        ParamType: 1644081168,
        InsId: 97,
      },
      {
        InsParamId: 320,
        ParamName: 'ENO',
        ParamType: 25772034,
        InsId: 97,
      },
      {
        InsParamId: 321,
        ParamName: 'READ',
        ParamType: 295518229,
        InsId: 97,
      },
      {
        InsParamId: 322,
        ParamName: 'RES',
        ParamType: 25772034,
        InsId: 97,
      },
    ],
    IsCanUse: true,
    Comment: '主站读',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 98,
    InsName: 'MBUSW',
    InsType: 3,
    InsGroup: 16,
    ParamsNumber: 10,
    Params: [
      {
        InsParamId: 323,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 98,
      },
      {
        InsParamId: 324,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 98,
      },
      {
        InsParamId: 325,
        ParamName: 'PORT',
        ParamType: 45072,
        InsId: 98,
      },
      {
        InsParamId: 326,
        ParamName: 'SLAVE',
        ParamType: 1644081154,
        InsId: 98,
      },
      {
        InsParamId: 327,
        ParamName: 'FUN',
        ParamType: 45072,
        InsId: 98,
      },
      {
        InsParamId: 328,
        ParamName: 'ADDR',
        ParamType: 412004356,
        InsId: 98,
      },
      {
        InsParamId: 329,
        ParamName: 'COUNT',
        ParamType: 1644081168,
        InsId: 98,
      },
      {
        InsParamId: 330,
        ParamName: 'WRITE',
        ParamType: 2046730261,
        InsId: 98,
      },
      {
        InsParamId: 331,
        ParamName: 'ENO',
        ParamType: 25772034,
        InsId: 98,
      },
      {
        InsParamId: 332,
        ParamName: 'RES',
        ParamType: 25772034,
        InsId: 98,
      },
    ],
    IsCanUse: true,
    Comment: '主站写',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 99,
    InsName: 'TCP_MBUSR',
    InsType: 3,
    InsGroup: 16,
    ParamsNumber: 11,
    Params: [
      {
        InsParamId: 333,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 99,
      },
      {
        InsParamId: 334,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 99,
      },
      {
        InsParamId: 335,
        ParamName: 'CHANNEL',
        ParamType: 45072,
        InsId: 99,
      },
      {
        InsParamId: 336,
        ParamName: 'FUN',
        ParamType: 45072,
        InsId: 99,
      },
      {
        InsParamId: 337,
        ParamName: 'ADDR',
        ParamType: 412004356,
        InsId: 99,
      },
      {
        InsParamId: 338,
        ParamName: 'COUNT',
        ParamType: 1644081168,
        InsId: 99,
      },
      {
        InsParamId: 339,
        ParamName: 'TIMEOUT',
        ParamType: 1644081168,
        InsId: 99,
      },
      {
        InsParamId: 340,
        ParamName: 'RETRY',
        ParamType: 1644081168,
        InsId: 99,
      },
      {
        InsParamId: 341,
        ParamName: 'ENO',
        ParamType: 0,
        InsId: 99,
      },
      {
        InsParamId: 342,
        ParamName: 'READ',
        ParamType: 295518229,
        InsId: 99,
      },
      {
        InsParamId: 343,
        ParamName: 'RES',
        ParamType: 25772034,
        InsId: 99,
      },
    ],
    IsCanUse: true,
    Comment: 'TCP读命令',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 100,
    InsName: 'TCP_MBUSW',
    InsType: 3,
    InsGroup: 16,
    ParamsNumber: 11,
    Params: [
      {
        InsParamId: 344,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 100,
      },
      {
        InsParamId: 345,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 100,
      },
      {
        InsParamId: 346,
        ParamName: 'CHANNEL',
        ParamType: 45072,
        InsId: 100,
      },
      {
        InsParamId: 347,
        ParamName: 'FUN',
        ParamType: 45072,
        InsId: 100,
      },
      {
        InsParamId: 348,
        ParamName: 'ADDR',
        ParamType: 412004356,
        InsId: 100,
      },
      {
        InsParamId: 349,
        ParamName: 'COUNT',
        ParamType: 1644081168,
        InsId: 100,
      },
      {
        InsParamId: 350,
        ParamName: 'WRITE',
        ParamType: 2046730261,
        InsId: 100,
      },
      {
        InsParamId: 351,
        ParamName: 'TIMEOUT',
        ParamType: 1644081168,
        InsId: 100,
      },
      {
        InsParamId: 352,
        ParamName: 'RETRY',
        ParamType: 1644081168,
        InsId: 100,
      },
      {
        InsParamId: 353,
        ParamName: 'ENO',
        ParamType: 0,
        InsId: 100,
      },
      {
        InsParamId: 354,
        ParamName: 'RES',
        ParamType: 25772034,
        InsId: 100,
      },
    ],
    IsCanUse: true,
    Comment: 'TCP写命令',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 101,
    InsName: 'TCP_RCV',
    InsType: 3,
    InsGroup: 9,
    ParamsNumber: 7,
    Params: [
      {
        InsParamId: 355,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 101,
      },
      {
        InsParamId: 356,
        ParamName: 'TIMEOUT',
        ParamType: 45060,
        InsId: 101,
      },
      {
        InsParamId: 357,
        ParamName: 'CHANNEL',
        ParamType: 45072,
        InsId: 101,
      },
      {
        InsParamId: 358,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 101,
      },
      {
        InsParamId: 359,
        ParamName: 'READ',
        ParamType: 8470530,
        InsId: 101,
      },
      {
        InsParamId: 360,
        ParamName: 'LEN',
        ParamType: 27082756,
        InsId: 101,
      },
      {
        InsParamId: 361,
        ParamName: 'RET',
        ParamType: 25772034,
        InsId: 101,
      },
    ],
    IsCanUse: true,
    Comment: 'TCP自由通讯：接收数据',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 102,
    InsName: 'TCP_XMT',
    InsType: 3,
    InsGroup: 9,
    ParamsNumber: 6,
    Params: [
      {
        InsParamId: 362,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 102,
      },
      {
        InsParamId: 363,
        ParamName: 'WRITE',
        ParamType: 8429570,
        InsId: 102,
      },
      {
        InsParamId: 364,
        ParamName: 'CHANNEL',
        ParamType: 45072,
        InsId: 102,
      },
      {
        InsParamId: 365,
        ParamName: 'LEN',
        ParamType: 27045904,
        InsId: 102,
      },
      {
        InsParamId: 366,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 102,
      },
      {
        InsParamId: 367,
        ParamName: 'RET',
        ParamType: 25772034,
        InsId: 102,
      },
    ],
    IsCanUse: true,
    Comment: 'TCP自由通讯：发送数据',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 103,
    InsName: 'SDO_WRITE',
    InsType: 3,
    InsGroup: 17,
    ParamsNumber: 10,
    Params: [
      {
        InsParamId: 368,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 103,
      },
      {
        InsParamId: 369,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 103,
      },
      {
        InsParamId: 370,
        ParamName: 'NODE',
        ParamType: 27176962,
        InsId: 103,
      },
      {
        InsParamId: 371,
        ParamName: 'INDEX',
        ParamType: 27176964,
        InsId: 103,
      },
      {
        InsParamId: 372,
        ParamName: 'SUBINDEX',
        ParamType: 27176962,
        InsId: 103,
      },
      {
        InsParamId: 373,
        ParamName: 'DATA',
        ParamType: 27172866,
        InsId: 103,
      },
      {
        InsParamId: 374,
        ParamName: 'DATALEN',
        ParamType: 27176962,
        InsId: 103,
      },
      {
        InsParamId: 375,
        ParamName: 'ENO',
        ParamType: 0,
        InsId: 103,
      },
      {
        InsParamId: 376,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 103,
      },
      {
        InsParamId: 377,
        ParamName: 'ERROR',
        ParamType: 27082760,
        InsId: 103,
      },
    ],
    IsCanUse: true,
    Comment: 'CANOPEN SDO写命令',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 104,
    InsName: 'SDO_READ',
    InsType: 3,
    InsGroup: 17,
    ParamsNumber: 10,
    Params: [
      {
        InsParamId: 378,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 104,
      },
      {
        InsParamId: 379,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 104,
      },
      {
        InsParamId: 380,
        ParamName: 'NODE',
        ParamType: 27176962,
        InsId: 104,
      },
      {
        InsParamId: 381,
        ParamName: 'INDEX',
        ParamType: 27176964,
        InsId: 104,
      },
      {
        InsParamId: 382,
        ParamName: 'SUBINDEX',
        ParamType: 27176962,
        InsId: 104,
      },
      {
        InsParamId: 383,
        ParamName: 'ENO',
        ParamType: 0,
        InsId: 104,
      },
      {
        InsParamId: 384,
        ParamName: 'DATA',
        ParamType: 27082754,
        InsId: 104,
      },
      {
        InsParamId: 385,
        ParamName: 'DATALEN',
        ParamType: 27082754,
        InsId: 104,
      },
      {
        InsParamId: 386,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 104,
      },
      {
        InsParamId: 387,
        ParamName: 'ERROR',
        ParamType: 27082760,
        InsId: 104,
      },
    ],
    IsCanUse: true,
    Comment: 'CANOPEN SDO读命令',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 105,
    InsName: 'CTU',
    InsType: 4,
    InsGroup: 10,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 388,
        ParamName: 'CU',
        ParamType: 1644077057,
        InsId: 105,
      },
      {
        InsParamId: 389,
        ParamName: 'R',
        ParamType: 1644077057,
        InsId: 105,
      },
      {
        InsParamId: 390,
        ParamName: 'PV',
        ParamType: 429830160,
        InsId: 105,
      },
      {
        InsParamId: 391,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 105,
      },
      {
        InsParamId: 392,
        ParamName: 'CV',
        ParamType: 295518224,
        InsId: 105,
      },
    ],
    IsCanUse: true,
    Comment: '加计数器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 106,
    InsName: 'CTD',
    InsType: 4,
    InsGroup: 10,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 393,
        ParamName: 'CD',
        ParamType: 1644077057,
        InsId: 106,
      },
      {
        InsParamId: 394,
        ParamName: 'LD',
        ParamType: 1644077057,
        InsId: 106,
      },
      {
        InsParamId: 395,
        ParamName: 'PV',
        ParamType: 429830160,
        InsId: 106,
      },
      {
        InsParamId: 396,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 106,
      },
      {
        InsParamId: 397,
        ParamName: 'CV',
        ParamType: 295518224,
        InsId: 106,
      },
    ],
    IsCanUse: true,
    Comment: '减计数器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 107,
    InsName: 'CTUD',
    InsType: 4,
    InsGroup: 10,
    ParamsNumber: 8,
    Params: [
      {
        InsParamId: 398,
        ParamName: 'CU',
        ParamType: 1644077057,
        InsId: 107,
      },
      {
        InsParamId: 399,
        ParamName: 'CD',
        ParamType: 1644077057,
        InsId: 107,
      },
      {
        InsParamId: 400,
        ParamName: 'R',
        ParamType: 1644077057,
        InsId: 107,
      },
      {
        InsParamId: 401,
        ParamName: 'LD',
        ParamType: 1644077057,
        InsId: 107,
      },
      {
        InsParamId: 402,
        ParamName: 'PV',
        ParamType: 429830160,
        InsId: 107,
      },
      {
        InsParamId: 403,
        ParamName: 'QU',
        ParamType: 27082753,
        InsId: 107,
      },
      {
        InsParamId: 404,
        ParamName: 'QD',
        ParamType: 27082753,
        InsId: 107,
      },
      {
        InsParamId: 405,
        ParamName: 'CV',
        ParamType: 295518224,
        InsId: 107,
      },
    ],
    IsCanUse: true,
    Comment: '加/减计数器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 108,
    InsName: 'HDEF',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 406,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 108,
      },
      {
        InsParamId: 407,
        ParamName: 'HSC',
        ParamType: 45072,
        InsId: 108,
      },
      {
        InsParamId: 408,
        ParamName: 'MODE',
        ParamType: 45072,
        InsId: 108,
      },
      {
        InsParamId: 409,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 108,
      },
    ],
    IsCanUse: true,
    Comment: '高速计数器定义',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 109,
    InsName: 'HSC',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 410,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 109,
      },
      {
        InsParamId: 411,
        ParamName: 'N',
        ParamType: 45072,
        InsId: 109,
      },
      {
        InsParamId: 412,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 109,
      },
    ],
    IsCanUse: true,
    Comment: '高速计数器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 110,
    InsName: 'PLS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 3,
    Params: [
      {
        InsParamId: 413,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 110,
      },
      {
        InsParamId: 414,
        ParamName: 'Q',
        ParamType: 45072,
        InsId: 110,
      },
      {
        InsParamId: 415,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 110,
      },
    ],
    IsCanUse: true,
    Comment: '脉冲输出',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 111,
    InsName: 'TON',
    InsType: 4,
    InsGroup: 12,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 416,
        ParamName: 'IN',
        ParamType: 1644077057,
        InsId: 111,
      },
      {
        InsParamId: 417,
        ParamName: 'PT',
        ParamType: 436121616,
        InsId: 111,
      },
      {
        InsParamId: 418,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 111,
      },
      {
        InsParamId: 419,
        ParamName: 'ET',
        ParamType: 295518224,
        InsId: 111,
      },
    ],
    IsCanUse: true,
    Comment: '接通延时定时器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 112,
    InsName: 'TONR',
    InsType: 4,
    InsGroup: 12,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 420,
        ParamName: 'IN',
        ParamType: 1644077057,
        InsId: 112,
      },
      {
        InsParamId: 421,
        ParamName: 'PT',
        ParamType: 436121616,
        InsId: 112,
      },
      {
        InsParamId: 422,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 112,
      },
      {
        InsParamId: 423,
        ParamName: 'ET',
        ParamType: 295518224,
        InsId: 112,
      },
    ],
    IsCanUse: true,
    Comment: '保持性定时器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 113,
    InsName: 'TOF',
    InsType: 4,
    InsGroup: 12,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 424,
        ParamName: 'IN',
        ParamType: 1644077057,
        InsId: 113,
      },
      {
        InsParamId: 425,
        ParamName: 'PT',
        ParamType: 436121616,
        InsId: 113,
      },
      {
        InsParamId: 426,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 113,
      },
      {
        InsParamId: 427,
        ParamName: 'ET',
        ParamType: 295518224,
        InsId: 113,
      },
    ],
    IsCanUse: true,
    Comment: '断开延时定时器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 114,
    InsName: 'TP',
    InsType: 4,
    InsGroup: 12,
    ParamsNumber: 4,
    Params: [
      {
        InsParamId: 428,
        ParamName: 'IN',
        ParamType: 1644077057,
        InsId: 114,
      },
      {
        InsParamId: 429,
        ParamName: 'PT',
        ParamType: 436121616,
        InsId: 114,
      },
      {
        InsParamId: 430,
        ParamName: 'Q',
        ParamType: 27082753,
        InsId: 114,
      },
      {
        InsParamId: 431,
        ParamName: 'ET',
        ParamType: 295518224,
        InsId: 114,
      },
    ],
    IsCanUse: true,
    Comment: '脉冲定时器',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 115,
    InsName: 'PID',
    InsType: 3,
    InsGroup: 13,
    ParamsNumber: 16,
    Params: [
      {
        InsParamId: 432,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 115,
      },
      {
        InsParamId: 433,
        ParamName: 'AUTO',
        ParamType: 1644077057,
        InsId: 115,
      },
      {
        InsParamId: 434,
        ParamName: 'PV',
        ParamType: 159948816,
        InsId: 115,
      },
      {
        InsParamId: 435,
        ParamName: 'SP',
        ParamType: 25731088,
        InsId: 115,
      },
      {
        InsParamId: 436,
        ParamName: 'X0',
        ParamType: 25206848,
        InsId: 115,
      },
      {
        InsParamId: 437,
        ParamName: 'KP',
        ParamType: 25206848,
        InsId: 115,
      },
      {
        InsParamId: 438,
        ParamName: 'TI',
        ParamType: 25206848,
        InsId: 115,
      },
      {
        InsParamId: 439,
        ParamName: 'TD',
        ParamType: 25206848,
        InsId: 115,
      },
      {
        InsParamId: 440,
        ParamName: 'PV_H',
        ParamType: 25731088,
        InsId: 115,
      },
      {
        InsParamId: 441,
        ParamName: 'PV_L',
        ParamType: 25731088,
        InsId: 115,
      },
      {
        InsParamId: 442,
        ParamName: 'XOUTP_H',
        ParamType: 25731088,
        InsId: 115,
      },
      {
        InsParamId: 443,
        ParamName: 'XOUTP_L',
        ParamType: 25731088,
        InsId: 115,
      },
      {
        InsParamId: 444,
        ParamName: 'CYCLE',
        ParamType: 25731104,
        InsId: 115,
      },
      {
        InsParamId: 445,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 115,
      },
      {
        InsParamId: 446,
        ParamName: 'XOUT',
        ParamType: 25247808,
        InsId: 115,
      },
      {
        InsParamId: 447,
        ParamName: 'XOUTP',
        ParamType: 294207504,
        InsId: 115,
      },
    ],
    IsCanUse: true,
    Comment: 'PID回路调节',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 116,
    InsName: 'EPHOME',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 14,
    Params: [
      {
        InsParamId: 448,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 116,
      },
      {
        InsParamId: 449,
        ParamName: 'AXIS',
        ParamType: 45072,
        InsId: 116,
      },
      {
        InsParamId: 450,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 116,
      },
      {
        InsParamId: 451,
        ParamName: 'HOME',
        ParamType: 1637785601,
        InsId: 116,
      },
      {
        InsParamId: 452,
        ParamName: 'NHOME',
        ParamType: 1637785601,
        InsId: 116,
      },
      {
        InsParamId: 453,
        ParamName: 'MODE',
        ParamType: 436121616,
        InsId: 116,
      },
      {
        InsParamId: 454,
        ParamName: 'DIRC',
        ParamType: 436121616,
        InsId: 116,
      },
      {
        InsParamId: 455,
        ParamName: 'MINF',
        ParamType: 27176968,
        InsId: 116,
      },
      {
        InsParamId: 456,
        ParamName: 'MAXF',
        ParamType: 27176968,
        InsId: 116,
      },
      {
        InsParamId: 457,
        ParamName: 'TIME',
        ParamType: 27176964,
        InsId: 116,
      },
      {
        InsParamId: 458,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 116,
      },
      {
        InsParamId: 459,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 116,
      },
      {
        InsParamId: 460,
        ParamName: 'ERR',
        ParamType: 27082753,
        InsId: 116,
      },
      {
        InsParamId: 461,
        ParamName: 'ERRID',
        ParamType: 27082754,
        InsId: 116,
      },
    ],
    IsCanUse: true,
    Comment: '回原点',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 117,
    InsName: 'EPABS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 11,
    Params: [
      {
        InsParamId: 462,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 117,
      },
      {
        InsParamId: 463,
        ParamName: 'AXIS',
        ParamType: 45072,
        InsId: 117,
      },
      {
        InsParamId: 464,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 117,
      },
      {
        InsParamId: 465,
        ParamName: 'MINF',
        ParamType: 27176968,
        InsId: 117,
      },
      {
        InsParamId: 466,
        ParamName: 'MAXF',
        ParamType: 27176968,
        InsId: 117,
      },
      {
        InsParamId: 467,
        ParamName: 'TIME',
        ParamType: 27176964,
        InsId: 117,
      },
      {
        InsParamId: 468,
        ParamName: 'POS',
        ParamType: 94285856,
        InsId: 117,
      },
      {
        InsParamId: 469,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 117,
      },
      {
        InsParamId: 470,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 117,
      },
      {
        InsParamId: 471,
        ParamName: 'ERR',
        ParamType: 27082753,
        InsId: 117,
      },
      {
        InsParamId: 472,
        ParamName: 'ERRID',
        ParamType: 27082754,
        InsId: 117,
      },
    ],
    IsCanUse: true,
    Comment: '绝对运动',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 118,
    InsName: 'EPREL',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 11,
    Params: [
      {
        InsParamId: 473,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 118,
      },
      {
        InsParamId: 474,
        ParamName: 'AXIS',
        ParamType: 45072,
        InsId: 118,
      },
      {
        InsParamId: 475,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 118,
      },
      {
        InsParamId: 476,
        ParamName: 'MINF',
        ParamType: 27176968,
        InsId: 118,
      },
      {
        InsParamId: 477,
        ParamName: 'MAXF',
        ParamType: 27176968,
        InsId: 118,
      },
      {
        InsParamId: 478,
        ParamName: 'TIME',
        ParamType: 27176964,
        InsId: 118,
      },
      {
        InsParamId: 479,
        ParamName: 'DIST',
        ParamType: 94285856,
        InsId: 118,
      },
      {
        InsParamId: 480,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 118,
      },
      {
        InsParamId: 481,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 118,
      },
      {
        InsParamId: 482,
        ParamName: 'ERR',
        ParamType: 27082753,
        InsId: 118,
      },
      {
        InsParamId: 483,
        ParamName: 'ERRID',
        ParamType: 27082754,
        InsId: 118,
      },
    ],
    IsCanUse: true,
    Comment: '相对运动',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 119,
    InsName: 'EPJOG',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 9,
    Params: [
      {
        InsParamId: 484,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 119,
      },
      {
        InsParamId: 485,
        ParamName: 'AXIS',
        ParamType: 45072,
        InsId: 119,
      },
      {
        InsParamId: 486,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 119,
      },
      {
        InsParamId: 487,
        ParamName: 'MINF',
        ParamType: 27176968,
        InsId: 119,
      },
      {
        InsParamId: 488,
        ParamName: 'DIRC',
        ParamType: 436121616,
        InsId: 119,
      },
      {
        InsParamId: 489,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 119,
      },
      {
        InsParamId: 490,
        ParamName: 'DONE',
        ParamType: 27082753,
        InsId: 119,
      },
      {
        InsParamId: 491,
        ParamName: 'ERR',
        ParamType: 27082753,
        InsId: 119,
      },
      {
        InsParamId: 492,
        ParamName: 'ERRID',
        ParamType: 27082754,
        InsId: 119,
      },
    ],
    IsCanUse: true,
    Comment: '点动',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 120,
    InsName: 'EPSTOP',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 6,
    Params: [
      {
        InsParamId: 493,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 120,
      },
      {
        InsParamId: 494,
        ParamName: 'AXIS',
        ParamType: 45072,
        InsId: 120,
      },
      {
        InsParamId: 495,
        ParamName: 'EXEC',
        ParamType: 1637785601,
        InsId: 120,
      },
      {
        InsParamId: 496,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 120,
      },
      {
        InsParamId: 497,
        ParamName: 'ERR',
        ParamType: 27082753,
        InsId: 120,
      },
      {
        InsParamId: 498,
        ParamName: 'ERRID',
        ParamType: 27082754,
        InsId: 120,
      },
    ],
    IsCanUse: true,
    Comment: '急停',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 121,
    InsName: 'SPD',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 499,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 121,
      },
      {
        InsParamId: 500,
        ParamName: 'HSC',
        ParamType: 45072,
        InsId: 121,
      },
      {
        InsParamId: 501,
        ParamName: 'TIME',
        ParamType: 27176964,
        InsId: 121,
      },
      {
        InsParamId: 502,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 121,
      },
      {
        InsParamId: 503,
        ParamName: 'PNUM',
        ParamType: 27082784,
        InsId: 121,
      },
    ],
    IsCanUse: true,
    Comment: '脉冲速率检测',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 122,
    InsName: 'LINCO',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 10,
    Params: [
      {
        InsParamId: 504,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 122,
      },
      {
        InsParamId: 505,
        ParamName: 'IN_L',
        ParamType: 436121616,
        InsId: 122,
      },
      {
        InsParamId: 506,
        ParamName: 'IN_H',
        ParamType: 436121616,
        InsId: 122,
      },
      {
        InsParamId: 507,
        ParamName: 'OUT_L',
        ParamType: 25210944,
        InsId: 122,
      },
      {
        InsParamId: 508,
        ParamName: 'OUT_H',
        ParamType: 25210944,
        InsId: 122,
      },
      {
        InsParamId: 509,
        ParamName: 'RATIO',
        ParamType: 45120,
        InsId: 122,
      },
      {
        InsParamId: 510,
        ParamName: 'IN',
        ParamType: 436117520,
        InsId: 122,
      },
      {
        InsParamId: 511,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 122,
      },
      {
        InsParamId: 512,
        ParamName: 'DOUT',
        ParamType: 27082784,
        InsId: 122,
      },
      {
        InsParamId: 513,
        ParamName: 'ROUT',
        ParamType: 25247808,
        InsId: 122,
      },
    ],
    IsCanUse: true,
    Comment: '线性化计算',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 123,
    InsName: 'CRC16',
    InsType: 3,
    InsGroup: 1,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 514,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 123,
      },
      {
        InsParamId: 515,
        ParamName: 'IN',
        ParamType: 27172866,
        InsId: 123,
      },
      {
        InsParamId: 516,
        ParamName: 'LEN',
        ParamType: 27176962,
        InsId: 123,
      },
      {
        InsParamId: 517,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 123,
      },
      {
        InsParamId: 518,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 123,
      },
    ],
    IsCanUse: true,
    Comment: 'CRC16算法',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
  {
    InsId: 124,
    InsName: 'CUS',
    InsType: 3,
    InsGroup: 15,
    ParamsNumber: 5,
    Params: [
      {
        InsParamId: 519,
        ParamName: 'EN',
        ParamType: 1644077057,
        InsId: 124,
      },
      {
        InsParamId: 520,
        ParamName: 'IN',
        ParamType: 27172866,
        InsId: 124,
      },
      {
        InsParamId: 521,
        ParamName: 'FUN',
        ParamType: 45072,
        InsId: 124,
      },
      {
        InsParamId: 522,
        ParamName: 'ENO',
        ParamType: 27082753,
        InsId: 124,
      },
      {
        InsParamId: 523,
        ParamName: 'OUT',
        ParamType: 27082754,
        InsId: 124,
      },
    ],
    IsCanUse: true,
    Comment: '定制功能块',
    IsIEC61131: true,
    InsTreeIconIndex: 21,
  },
];
